.dev_template:
    environment:
        name: dev
    rules:
        - if: '$CI_COMMIT_BRANCH != "main"'

build_dev:
    extends:
        - .dev_template
        - .build_template

validate_network_dev:
    extends:
        - .dev_template
        - .validate_network_template

validate_db_dev:
    extends:
        - .dev_template
        - .validate_db_template

validate_app_dev:
    extends:
        - .dev_template
        - .validate_app_template

plan_network_dev:
    extends:
        - .dev_template
        - .plan_network_template

plan_db_dev:
    extends:
        - .dev_template
        - .plan_db_template

plan_app_dev:
    extends:
        - .dev_template
        - .plan_app_template

apply_network_dev:
    extends:
        - .dev_template
        - .apply_network_template

apply_db_dev:
    extends:
        - .dev_template
        - .apply_db_template

apply_app_dev:
    extends:
        - .dev_template
        - .apply_app_template

#TODO
#db_setup_dev:
#    extends:
#        - .dev_template
#        - .db_setup_template
