stages:
    - build
    - validate
    - plan
    - apply

include:
    - local: 'cicd/job_templates.yml'
    - local: 'cicd/dev.yml'
    - local: 'cicd/test.yml'
    - local: 'cicd/PROD.yml'

variables:
    GITLAB_ENV: "$CI_ENVIRONMENT_NAME"
    TF_BACKEND_BUCKET: "fidocred-${GITLAB_ENV}-tfstate"
    TF_BACKEND_REGION: "us-east-1"
    TF_BACKEND_LOCK_TABLE: "fidocred-${GITLAB_ENV}-locks"
    TF_BACKEND_CONFIG: >
        -backend-config=bucket=${TF_BACKEND_BUCKET}
        -backend-config=region=${TF_BACKEND_REGION}
        -backend-config=dynamodb_table=${TF_BACKEND_LOCK_TABLE}
        -backend-config=encrypt=true
    TF_BACKEND_KEY_NETWORK: -backend-config=key=network/terraform.tfstate
    TF_BACKEND_KEY_DB:      -backend-config=key=db/terraform.tfstate
    TF_BACKEND_KEY_APP:     -backend-config=key=app/terraform.tfstate
    TF_NETWORK_VARS: >
        -var="gitlab_env=${GITLAB_ENV}"
    TF_DB_VARS: >
        -var="gitlab_env=${GITLAB_ENV}"
        -var="remote_state_bucket=${TF_BACKEND_BUCKET}
        -var="remote_state_region=${TF_BACKEND_REGION}
        -var="remote_state_key=network/terraform.tfstate"
        -var="remote_state_lock_table=${TF_BACKEND_LOCK_TABLE}
    TF_APP_VARS: >
        -var="gitlab_env=${GITLAB_ENV}"
        -var="remote_state_bucket=${TF_BACKEND_BUCKET}
        -var="remote_state_region=${TF_BACKEND_REGION}
        -var="remote_state_key=db/terraform.tfstate"
        -var="remote_state_lock_table=${TF_BACKEND_LOCK_TABLE}
