stages:
    - build
    - validate
    - plan
    - apply

include:
    - local: 'cicd/job_templates.yml'
    - local: 'cicd/dev.yml'
    - local: 'cicd/test.yml'
    - local: 'cicd/PROD.yml'

variables:
    OT_BACKEND_CONFIG: |
        backend "gitlab" {
            project = "FidoCred/fidocred-api"
            environment = "$CI_ENVIRONMENT_NAME"
        }
    gitlab_env: "$CI_ENVIRONMENT_NAME"
