.PROD_template:
    environment:
        name: PROD
    rules:
        - if: '$CI_COMMIT_BRANCH == "main" && $CI_COMMIT_TAG'

build_PROD:
    extends:
        - .PROD_template
        - .build_template

validate_PROD:
    extends:
        - .PROD_template
        - .validate_template

plan_PROD:
    extends:
        - .PROD_template
        - .plan_template

apply_PROD:
    extends:
        - .PROD_template
        - .apply_template
    script:
        - echo "Production releases not supported yet."
        - exit 1
