.plan_template:
    stage: plan
    image:
        name: hashicorp/terraform:1.6.0
        entrypoint: [""]
    environment:
        name: $ENV
    before_script:
        - echo "HELLO"
        - terraform --version
    script:
        - echo "HELLO"
        - terraform init -backend-config="path=backend-${ENV}.tfstate"
        - terraform plan -out="${ENV}.tfplan"
    artifacts:
        paths:
            - "${ENV}.tfplan"
        expire_in: 6 hours

.apply_template:
    stage: apply
    image: hashicorp/terraform:1.6.0
    environment:
        name: $ENV
    script:
        - echo "HELLO"
        - terraform apply "${ENV}.tfplan"
