.validate_template:
    stage: validate
    image:
        name: hashicorp/terraform:1.6.0
        entrypoint: [""]
    environment:
        name: $ENV
    script:
        - cd infra
        - terraform init -backend=false
        - terraform validate

.plan_template:
    stage: plan
    image:
        name: hashicorp/terraform:1.6.0
        entrypoint: [""]
    environment:
        name: $ENV
    script:
        - cd infra
        - terraform init -backend-config="backend-${ENV}.tf"
        - terraform plan -out="${ENV}.tfplan" -var="env_name=${ENV}"
    artifacts:
        paths:
            - "${ENV}.tfplan"
        expire_in: 6 hours

.apply_template:
    stage: apply
    image:
        name: hashicorp/terraform:1.6.0
        entrypoint: [""]
    environment:
        name: $ENV
    script:
        - cd infra
        - terraform init -backend-config="backend-${ENV}.tf"
        - terraform apply "${ENV}.tfplan"
