.validate_template:
    stage: validate
    image:
        name: oowy/opentofu:1.9.1-alpine3.20
    environment:
        name: $ENV
    script:
        - cd infra
        - tofu init
        - tofu validate

.plan_template:
    stage: plan
    image:
        name: oowy/opentofu:1.9.1-alpine3.20
    environment:
        name: $ENV
    script:
        - cd infra
        - tofu init
        - tofu plan -out="${ENV}.tfplan" -var="env_name=${ENV}"
    artifacts:
        paths:
            - "${ENV}.tfplan"
        expire_in: 6 hours

.apply_template:
    stage: apply
    image:
        name: oowy/opentofu:1.9.1-alpine3.20
    environment:
        name: $ENV
    script:
        - cd infra
        - tofu init
        - tofu apply "${ENV}.tfplan"
