.validate_template:
    stage: validate
    image:
        name: oowy/opentofu:1.9.1-alpine3.20
        entrypoint: [""]
    environment:
        name: $ENV
    script:
        - cd infra
        - opentofu init -backend=false
        - opentofu validate

.plan_template:
    stage: plan
    image:
        name: oowy/opentofu:1.9.1-alpine3.20
        entrypoint: [""]
    environment:
        name: $ENV
    script:
        - cd infra
        - opentofu init -backend-config="backend-${ENV}.tf"
        - opentofu plan -out="${ENV}.tfplan" -var="env_name=${ENV}"
    artifacts:
        paths:
            - "${ENV}.tfplan"
        expire_in: 6 hours

.apply_template:
    stage: apply
    image:
        name: oowy/opentofu:1.9.1-alpine3.20
        entrypoint: [""]
    environment:
        name: $ENV
    script:
        - cd infra
        - opentofu init -backend-config="backend-${ENV}.tf"
        - opentofu apply "${ENV}.tfplan"

.fail_pipeline_on_failure: &fail_pipeline_on_failure
  script:
    - |
      if [[ "$CI_JOB_STATUS" == "failed" ]]; then
        echo "Previous stage failed – stopping pipeline"
        exit 1
      fi
  allow_failure: false
  when: always
  stage: will_be_overwritten
