.test_template:
    variables:
        ENV: test
    rules:
        - if: '$CI_COMMIT_BRANCH == "main"'
          when: always

validate_test:
    extends:
        - .test_template
        - .validate_template

plan_test:
    extends:
        - .test_template
        - .plan_template

apply_test:
    extends:
        - .test_template
        - .apply_template
